<a href="https://colab.research.google.com/github/Aravindr017/Election_Dataset_Portugal-Regression/blob/main/Model/PipelineSkeleton.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Github Commands

### <u><i>Clone the repository (once)</u></i>
`git clone https://github.com/Aravindr017/Election_Dataset_Portugal-Regression.git`

### <u><i>Enter the project</u></i>
`cd Election_Dataset_Portugal-Regression`

### <u><i>Create your branch (once)</u></i>
`git checkout -b <branch-name>`

### <u><i>Before starting new work</u></i>
`git checkout main`<br>
`git pull origin main`<br>
`git checkout <branch-name>`<br>
`git merge main`<br>

### <u><i>After making changes</u></i>
`git status`<br>
`git add .`<br>
`git commit -m "Describe your changes"`<br>

### <u><i>Upload your branch</u></i>
`git push --set-upstream origin <branch-name>`   # first push <br>
`git push`                                       # later pushes

# Importing Libraries

In [5]:
# basic python libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [10]:
filepath = '/content/drive/MyDrive/AI ML/IRP/datasets/ElectionData.csv'
df = pd.read_csv(filepath)
df.head(2)

,TimeElapsed,time,territoryName,totalMandates,availableMandates,numParishes,numParishesApproved,blankVotes,blankVotesPercentage,nullVotes,...,pre.votersPercentage,pre.subscribedVoters,pre.totalVoters,Party,Mandates,Percentage,validVotesPercentage,Votes,Hondt,FinalMandates
0,0,2019-10-06 20:10:02,Território Nacional,0,226,3092,1081,9652,2.5,8874,...,52.66,813743,428546,PS,0,38.29,40.22,147993,94,106
1,0,2019-10-06 20:10:02,Território Nacional,0,226,3092,1081,9652,2.5,8874,...,52.66,813743,428546,PPD/PSD,0,33.28,34.95,128624,81,77

# EDA (Explodatory Data Analysis)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21643 entries, 0 to 21642
Data columns (total 28 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   TimeElapsed               21643 non-null  int64
 1   time                      21643 non-null  object
 2   territoryName             21643 non-null  object
 3   totalMandates             21643 non-null  int64
 4   availableMandates         21643 non-null  int64
 5   numParishes               21643 non-null  int64
 6   numParishesApproved       21643 non-null  int64
 7   blankVotes                21643 non-null  int64
 8   blankVotesPercentage      21643 non-null  float64
 9   nullVotes                 21643 non-null  int64
 10  nullVotesPercentage       21643 non-null  float64
 11  votersPercentage          21643 non-null  float64
 12  subscribedVoters          21643 non-null  int64
 13  totalVoters               21643 non-null  int64
 14  pre.blankVotes            21643 non-null  int64
 15  pre.blankVotesPercentage  21643 non-null  float64
 16  pre.nullVotes             21643 non-null  int64
 17  pre.nullVotesPercentage   21643 non-null  float64
 18  pre.votersPercentage      21643 non-null  float64
 19  pre.subscribedVoters      21643 non-null  int64
 20  pre.totalVoters           21643 non-null  int64
 21  Party                     21643 non-null  object
 22  Mandates                  21643 non-null  int64
 23  Percentage                21643 non-null  float64
 24  validVotesPercentage      21643 non-null  float64
 25  Votes                     21643 non-null  int64
 26  Hondt                     21643 non-null  int64
 27  FinalMandates             21643 non-null  int64
dtypes: float64(8), int64(17), object(3)
memory usage: 4.6+ MB

In [13]:
df.shape

(21643, 28)

In [14]:
df.describe()

,TimeElapsed,totalMandates,availableMandates,numParishes,numParishesApproved,blankVotes,blankVotesPercentage,nullVotes,nullVotesPercentage,votersPercentage,...,pre.nullVotesPercentage,pre.votersPercentage,pre.subscribedVoters,pre.totalVoters,Mandates,Percentage,validVotesPercentage,Votes,Hondt,FinalMandates
count,21643.000000,21643.000000,21643.000000,21643.000000,21643.000000,21643.000000,21643.000000,21643.000000,21643.000000,21643.000000,...,21643.000000,21643.000000,2.164300e+04,2.164300e+04,21643.000000,21643.000000,21643.000000,2.164300e+04,21643.000000,21643.000000
mean,133.146052,11.544795,11.499284,309.956013,261.090237,8875.066673,2.621629,6148.068752,1.961471,51.983722,...,1.777442,54.549372,6.378503e+05,3.594932e+05,0.565495,4.968484,5.207232,1.585209e+04,1.126138,1.126138
std,77.651193,31.314567,31.738783,659.055911,583.377428,21484.874088,0.795289,14735.469269,0.375250,4.854380,...,0.388798,4.964948,1.544418e+06,8.763729e+05,4.421804,10.379967,10.881108,9.310605e+04,6.293552,6.872644
min,0.000000,0.000000,0.000000,54.000000,3.000000,19.000000,0.530000,39.000000,1.340000,35.980000,...,1.140000,40.870000,6.383000e+03,3.215000e+03,0.000000,0.020000,0.020000,1.000000e+00,0.000000,0.000000
25%,65.000000,1.000000,0.000000,75.000000,67.000000,1188.000000,2.230000,1094.000000,1.720000,50.290000,...,1.520000,51.210000,1.289260e+05,6.964400e+04,0.000000,0.220000,0.230000,2.360000e+02,0.000000,0.000000
50%,135.000000,4.000000,3.000000,147.000000,120.000000,2998.000000,2.640000,2232.000000,1.870000,53.130000,...,1.690000,56.260000,2.284970e+05,1.102730e+05,0.000000,0.620000,0.650000,7.900000e+02,0.000000,0.000000
75%,200.000000,9.000000,9.000000,242.000000,208.000000,6889.000000,2.980000,4121.000000,2.230000,54.550000,...,1.970000,58.220000,3.933140e+05,2.276200e+05,0.000000,3.010000,3.160000,4.510000e+03,0.000000,0.000000
max,265.000000,226.000000,226.000000,3092.000000,3092.000000,129599.000000,5.460000,88539.000000,3.350000,59.870000,...,3.120000,62.580000,9.439701e+06,5.380451e+06,106.000000,49.110000,51.420000,1.866407e+06,94.000000,106.000000

In [15]:
df.isnull().sum()

TimeElapsed                 0
time                        0
territoryName               0
totalMandates               0
availableMandates           0
numParishes                 0
numParishesApproved         0
blankVotes                  0
blankVotesPercentage        0
nullVotes                   0
nullVotesPercentage         0
votersPercentage            0
subscribedVoters            0
totalVoters                 0
pre.blankVotes              0
pre.blankVotesPercentage    0
pre.nullVotes               0
pre.nullVotesPercentage     0
pre.votersPercentage        0
pre.subscribedVoters        0
pre.totalVoters             0
Party                       0
Mandates                    0
Percentage                  0
validVotesPercentage        0
Votes                       0
Hondt                       0
FinalMandates               0
dtype: int64

In [16]:
df.duplicated().sum()

np.int64(0)

## Data Visualization - Plots

### Histograms

### Box-Plots

### Scatterplots

# Data Preprocessing

## Duplicate Removal

## Missing Value Handling

 - Symmetric data - Mean
 - Skewed data - Median
 - Categorical data - Mode

## Outlier handling

### Boxplot After Handling Outliers

## Scaling Numerical Columns

- Minmax Scaling if data distribution is skewed
- Standard Scaling if data distribution is symmetric

`note : only do scaling on continuous numerical values`

## Encoding Categorical Columns

 - One-hot encoding for all feature columns
 - Label/Ordinal Encoding for target column

 ` note : Try to split target and features before encoding because may accidently do same encoding to target if it is categorical`

## Data Splitting

- Target and Features
- Target is 'y' and Features is 'X'

# Feature Engineering

- Adding new columns, creating new columns from existing one if needed.

# Model Building (if needed)

`note : We have to create a regression model.`

# Evaluating the model

As we are creating a regression model we use the following metrices:
 - Mean Absolute Error (MAE)
 - Mean Squared Error (MSE)
 - R2 Score
 - Root Mean Squared Error (RMSE)